apiVersion: chaos-mesh.org/v1alpha1
kind: SecurityChaos
metadata:
  name: security-chaos-run-as-root
  namespace: chaos-testing
spec:
  action: create-pod
  podsecuritycontext:
    runAsUser: 0
  namespace: default
  scheduler:
    cron: "@every 1m"
