apiVersion: chaos-mesh.org/v1alpha1
kind: SecurityChaos
metadata:
  name: security-chaos-delete-file
  namespace: chaos-testing
spec:
  action: delete-file
  mode: one
  uid: 1000
  gid: 1234
  pvclaim: "delete-file-pv-claim"
  volumemountpath: "super/data/"
  selector:
    labelSelectors:
      'app': 'delete-file-pod'
  scheduler:
    cron: "@every 1m"
