apiVersion: chaos-mesh.org/v1alpha1
kind: SecurityChaos
metadata:
  name: security-chaos-delete-file
  namespace: chaos-testing
spec:
  action: delete-file
  mode: one
  selector:
    labelSelectors:
      'app': 'delete-file-pod'
  scheduler:
    cron: "@every 1m"
