apiVersion: chaos-mesh.org/v1alpha1
kind: SecurityChaos
metadata:
  name: security-chaos-kubelet-api
  namespace: chaos-testing
spec:
  action: kubelet-api
  node: minikube
  scheduler:
    cron: "@every 1m"
