apiVersion: chaos-mesh.org/v1alpha1
kind: SecurityChaos
metadata:
  name: security-chaos-run-as-privileged
  namespace: chaos-testing
spec:
  action: run-as-privileged
  namespace: default
  scheduler:
    cron: "@every 1m"
