apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyrole
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - example
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policybinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: policyrole
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
