apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-creator
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["pods", "jobs", "pods/exec","secrets"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["users"]
  verbs: ["impersonate"]
