apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-chaos-global
subjects:
- kind: User
  name: system:serviceaccount:chaos-testing:chaos-controller-manager
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: chaos-creator
  apiGroup: rbac.authorization.k8s.io
