apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: chaos-creator
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  #
  # at the HTTP level, the name of the resource for accessing Deployment
  # objects is "deployments"
  resources: ["deployments", "replicationcontrollers", "pods", "jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
