apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-creator
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["pods", "jobs", "pods/exec"]
  verbs: ["get", "create", "delete"]
