apiVersion: v1
kind: Pod
metadata:
  name: create-file-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1234
    fsGroup: 1234
  volumes:
    - name: delete-file-pv-storage
      persistentVolumeClaim:
        claimName: delete-file-pv-claim
  containers:
  - name: create-file-container
    image: busybox
    command: ["touch"]
    #args: ["hello"]
    args: ["super/data/dummyfile"]
    #args: ["HOSTNAME", "KUBERNETES_PORT"]
    volumeMounts:
      - mountPath: "/super/data"
        name: delete-file-pv-storage
  restartPolicy: Never
