apiVersion: v1
kind: PersistentVolume
metadata:
  name: delete-file-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: delete-file-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delete-file-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delete-file-pod
  template:
    metadata:
      labels:
        app: delete-file-pod
    spec:
      securityContext:
        runAsUser: 1000
      volumes:
        - name: delete-file-pv-storage
          persistentVolumeClaim:
            claimName: delete-file-pv-claim
      containers:
      - name: delete-file-container
        image: hendrikmaus/kubernetes-dummy-image
        volumeMounts:
          - mountPath: "/super/data"
            name: delete-file-pv-storage
